# directory in a case folder.
CASECONFIG=$CASEDIR/config
CASERUN=$CASEDIR/run
CASEWORK=$CASEDIR/work
CASEOUT=$CASEDIR/output
CASELOG=$CASEDIR/log
CASEPLOT=$CASEDIR/plot
CASERES=$CASEDIR/restart
CASEBND=$CASEDIR/bnddata
CASEFFE=$CASEBND/FFE
CASEFTA=$CASEBND/Fta
WebCaseDir=$WebDir/$CASENAME

